# Generated by Django 5.0.1 on 2024-02-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_productsdescuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersForRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ShipRegion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='productsdescuento',
            name='Discontinued',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
