# Generated by Django 5.0.1 on 2024-02-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_dateexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateexcel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
